### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by commjoen**
Added a material design Android app.

### CODE REVIEW

**Comment by awulder** [comment]
I can't merge your PR...

**Comment by jbnicolai** [comment]
@awulder why not?

**Comment by awulder** [comment]
It seems that master needs to be merged first.

**Comment by agemooij** [comment]
That's the problem with online editing. Easiest is to close this PR and re-add a new commit or PR. Otherwise use the command line and merge the branches ;)

**Comment by agemooij** [comment]
Tell you what, I'll do it for you

**Comment by agemooij** [comment]
Done

**Comment by jbnicolai** [comment]
@agemooij looks like we did it at exactly the same moment :p

**Comment by jbnicolai** [comment]
@agemooij although you destroyed the original author :scream:

**Comment by agemooij** [comment]
Damn. Just trying to keep things simple ;)

**Comment by jbnicolai** [comment]
Haha me too, I just did a `git -am <this pages url> --signof && git push`

**Pull request closed without merging**
